import { Challenge } from './challenge.types';

export const CHALLENGE_CATALOG: readonly Challenge[] = [
  // ==========================================
  // --- 1. FLUENCY & PACING DRILLS (7) ---
  // ==========================================
  {
    id: 'fluency-filler-reduction-45',
    title: '45-Second Filler Detox',
    shortDescription: 'Speak for 45 seconds continuously while eliminating verbal fillers (um, uh, like).',
    whyItMatters: 'Replacing filler sounds with confident silence instantly enhances authority.',
    targetSkill: 'Fluency',
    challengeType: 'timed_speaking',
    difficultyLevel: 1,
    difficultyLabel: 'Beginner',
    durationSeconds: 45,
    prompt: 'Describe your favorite productivity habit and explain why it works for you.',
    instructions: [
      'Speak at a calm, controlled tempo.',
      'If you lose your train of thought, pause silently for 1 second instead of saying "um" or "like".',
      'Keep going until the 45-second timer concludes.',
    ],
    expectedBehavior: 'Zero or minimal filler words with steady, deliberate cadence.',
    xpReward: 30,
    goalTags: ['EVERYDAY_COMMUNICATION', 'PUBLIC_SPEAKING', 'WORKPLACE_COMMUNICATION'],
    targetWeakness: 'filler_dependency',
  },
  {
    id: 'fluency-rapid-pitch-60',
    title: '60-Second Momentum Drill',
    shortDescription: 'Deliver a continuous 60-second pitch without stalling or second-guessing.',
    whyItMatters: 'Builds flow state and trains you to think ahead while speaking.',
    targetSkill: 'Fluency',
    challengeType: 'rapid_response',
    difficultyLevel: 2,
    difficultyLabel: 'Intermediate',
    durationSeconds: 60,
    prompt: 'Tell me about your latest project or coursework in 60 seconds.',
    instructions: [
      'Start with a 1-sentence summary of what it is.',
      'Highlight 1 core challenge you solved.',
      'Finish with the real-world value or lesson learned.',
    ],
    expectedBehavior: 'Continuous speech flow maintaining 130-150 WPM.',
    xpReward: 30,
    goalTags: ['JOB_INTERVIEWS', 'CAMPUS_PLACEMENTS', 'WORKPLACE_COMMUNICATION'],
    targetWeakness: 'slow_delivery',
  },
  {
    id: 'fluency-deliberate-pause-45',
    title: 'The Power of the Silent Pause',
    shortDescription: 'Deliver an update using deliberate 1-second silent pauses between major ideas.',
    whyItMatters: 'Strategic pauses allow the listener to absorb key points and prevent rushed delivery.',
    targetSkill: 'Fluency',
    challengeType: 'timed_speaking',
    difficultyLevel: 1,
    difficultyLabel: 'Beginner',
    durationSeconds: 45,
    prompt: 'Explain two important reasons why continuous learning matters in modern careers.',
    instructions: [
      'State Point 1, then pause in complete silence for 1 full second.',
      'State Point 2, and again pause silently before your conclusion.',
      'Never fill the silence with vocal hesitation sounds.',
    ],
    expectedBehavior: 'Clean deliberate pauses without filler sounds.',
    xpReward: 30,
    goalTags: ['PUBLIC_SPEAKING', 'WORKPLACE_COMMUNICATION', 'JOB_INTERVIEWS'],
    targetWeakness: 'filler_dependency',
  },
  {
    id: 'fluency-breath-control-60',
    title: 'Controlled Cadence Sprint',
    shortDescription: 'Maintain a steady, measured pace without rushing through complex thoughts.',
    whyItMatters: 'Rushed delivery signals nervousness; controlled cadence projects command and calm.',
    targetSkill: 'Fluency',
    challengeType: 'timed_speaking',
    difficultyLevel: 2,
    difficultyLabel: 'Intermediate',
    durationSeconds: 60,
    prompt: 'Walk me through how a team should handle an urgent deadline when requirements change.',
    instructions: [
      'Inhale calmly before starting each major sentence.',
      'Maintain an even tempo between 125 and 145 WPM.',
      'Emphasize key operative words with deliberate vocal weight.',
    ],
    expectedBehavior: 'Even cadence without rapid rushed bursts.',
    xpReward: 30,
    goalTags: ['WORKPLACE_COMMUNICATION', 'GROUP_DISCUSSIONS'],
    targetWeakness: 'rushed_delivery',
  },
  {
    id: 'fluency-spontaneous-stream-75',
    title: 'Stream of Thought Pivot',
    shortDescription: 'Connect two unrelated topics smoothly without breaking speech continuity.',
    whyItMatters: 'Sharpens mental agility for handling unexpected meeting questions.',
    targetSkill: 'Fluency',
    challengeType: 'rapid_response',
    difficultyLevel: 2,
    difficultyLabel: 'Intermediate',
    durationSeconds: 75,
    prompt: 'Start by describing a book or movie you love, then pivot to what it teaches about modern leadership.',
    instructions: [
      'Spend 35 seconds on the book/movie summary.',
      'Use a bridging transition (e.g. "This directly mirrors how leaders must...")',
      'Spend the remaining 40 seconds on the leadership takeaway.',
    ],
    expectedBehavior: 'Seamless logical pivot without hesitation pauses.',
    xpReward: 35,
    goalTags: ['PUBLIC_SPEAKING', 'EVERYDAY_COMMUNICATION'],
    targetWeakness: 'slow_delivery',
  },
  {
    id: 'fluency-storytelling-arc-60',
    title: 'The 3-Act Mini Story',
    shortDescription: 'Narrate a memorable personal anecdote with a clear beginning, middle, and climax.',
    whyItMatters: 'Storytelling makes information memorable and emotionally engaging.',
    targetSkill: 'Fluency',
    challengeType: 'storytelling',
    difficultyLevel: 2,
    difficultyLabel: 'Intermediate',
    durationSeconds: 60,
    prompt: 'Tell a 60-second story about a time when an unexpected obstacle forced you to adapt quickly.',
    instructions: [
      'Act 1 - Setup (15s): What was supposed to happen.',
      'Act 2 - Crisis (30s): The sudden obstacle and what you did.',
      'Act 3 - Resolution (15s): The outcome and takeaway.',
    ],
    expectedBehavior: 'Vivid narrative flow with clear dynamic pacing changes.',
    xpReward: 30,
    goalTags: ['PUBLIC_SPEAKING', 'EVERYDAY_COMMUNICATION', 'JOB_INTERVIEWS'],
    targetWeakness: 'unclear_structure',
  },
  {
    id: 'fluency-executive-summary-90',
    title: 'Executive Multi-Minute Stamina',
    shortDescription: 'Deliver a structured 90-second strategic briefing without running out of breath.',
    whyItMatters: 'Senior presentations require sustained vocal energy and thought management.',
    targetSkill: 'Fluency',
    challengeType: 'timed_speaking',
    difficultyLevel: 3,
    difficultyLabel: 'Advanced',
    durationSeconds: 90,
    prompt: 'Deliver a comprehensive 90-second proposal for adopting a new tool or methodology in your organization.',
    instructions: [
      'Phase 1: The core problem and business cost (30s).',
      'Phase 2: The proposed solution and implementation path (35s).',
      'Phase 3: The expected return on investment (25s).',
    ],
    expectedBehavior: 'Continuous, high-stamina delivery without energy drops.',
    xpReward: 40,
    goalTags: ['WORKPLACE_COMMUNICATION', 'JOB_INTERVIEWS'],
    targetWeakness: 'slow_delivery',
  },

  // ==========================================
  // --- 2. CLARITY & STRUCTURE DRILLS (7) ---
  // ==========================================
  {
    id: 'clarity-explain-simply-60',
    title: 'Explain to a 10-Year-Old',
    shortDescription: 'Explain a technical or complex concept in simple, accessible language.',
    whyItMatters: 'True mastery of a subject is proven by making it crystal clear to anyone.',
    targetSkill: 'Clarity',
    challengeType: 'explain_simply',
    difficultyLevel: 2,
    difficultyLabel: 'Intermediate',
    durationSeconds: 60,
    prompt: 'Explain how Cloud Computing or APIs work to someone with zero technical background.',
    instructions: [
      'Use a physical real-world analogy (e.g. restaurant kitchen or postal service).',
      'Avoid technical acronyms and jargon.',
      'Keep sentence structures under 15 words each.',
    ],
    expectedBehavior: 'Jargon-free clarity using short, punchy sentence structures.',
    xpReward: 30,
    goalTags: ['CAMPUS_PLACEMENTS', 'WORKPLACE_COMMUNICATION', 'PUBLIC_SPEAKING'],
    targetWeakness: 'excessive_jargon',
  },
  {
    id: 'clarity-concise-answer-45',
    title: 'The 45-Second Executive Update',
    shortDescription: 'Summarize a complex weekly status update in under 45 seconds.',
    whyItMatters: 'Executives and recruiters value brevity and high information density.',
    targetSkill: 'Clarity',
    challengeType: 'concise_answer',
    difficultyLevel: 3,
    difficultyLabel: 'Advanced',
    durationSeconds: 45,
    prompt: 'Give a 45-second status update on an initiative where something went wrong and how you fixed it.',
    instructions: [
      'Headline (10s): State current status and the main blocker.',
      'Action (20s): Outline the immediate fix deployed.',
      'Next Step (15s): Give the clear timeline to completion.',
    ],
    expectedBehavior: 'High information density with structured transitions.',
    xpReward: 30,
    goalTags: ['WORKPLACE_COMMUNICATION', 'JOB_INTERVIEWS'],
    targetWeakness: 'overlong_answers',
  },
  {
    id: 'clarity-bottom-line-first-30',
    title: 'BLUF: Bottom Line Up Front',
    shortDescription: 'State the core decision/recommendation in the very first sentence.',
    whyItMatters: 'Busy stakeholders need the takeaway before the supporting details.',
    targetSkill: 'Clarity',
    challengeType: 'concise_answer',
    difficultyLevel: 1,
    difficultyLabel: 'Beginner',
    durationSeconds: 30,
    prompt: 'Should remote teams prioritize asynchronous documentation or live meetings? Deliver your verdict.',
    instructions: [
      'Sentence 1: Unambiguous bottom line ("My recommendation is...").',
      'Sentence 2 & 3: The 2 highest-impact supporting facts.',
      'Stop cleanly before the 30-second mark.',
    ],
    expectedBehavior: 'Immediate clear thesis without throat-clearing.',
    xpReward: 25,
    goalTags: ['WORKPLACE_COMMUNICATION', 'JOB_INTERVIEWS'],
    targetWeakness: 'weak_opening',
  },
  {
    id: 'clarity-rule-of-three-60',
    title: 'The Rule of Three Framework',
    shortDescription: 'Organize any response into exactly three clear, numbered pillars.',
    whyItMatters: 'Human memory naturally retains information grouped in triads.',
    targetSkill: 'Clarity',
    challengeType: 'explain_simply',
    difficultyLevel: 1,
    difficultyLabel: 'Beginner',
    durationSeconds: 60,
    prompt: 'What are the 3 essential qualities of an exceptional team member?',
    instructions: [
      'Introduce: "There are three core traits: First... Second... Third..."',
      'Give 1 concise example for each trait.',
      'Synthesize with a 1-sentence wrap-up.',
    ],
    expectedBehavior: 'Structured 3-part delivery with signposting words.',
    xpReward: 30,
    goalTags: ['CAMPUS_PLACEMENTS', 'JOB_INTERVIEWS', 'GROUP_DISCUSSIONS'],
    targetWeakness: 'unclear_structure',
  },
  {
    id: 'clarity-complex-system-75',
    title: 'Deconstructing Technical Complexity',
    shortDescription: 'Break down a multi-component architecture into logical layers.',
    whyItMatters: 'Technical leaders must bridge high-level architecture with practical execution.',
    targetSkill: 'Clarity',
    challengeType: 'explain_simply',
    difficultyLevel: 3,
    difficultyLabel: 'Advanced',
    durationSeconds: 75,
    prompt: 'Explain how user authentication and security tokens flow through a modern web application.',
    instructions: [
      'Start with the user action (Login trigger).',
      'Explain the middle tier (Token generation & validation).',
      'Finish with the database & session state layer.',
    ],
    expectedBehavior: 'Step-by-step sequential clarity without technical hand-waving.',
    xpReward: 35,
    goalTags: ['CAMPUS_PLACEMENTS', 'JOB_INTERVIEWS'],
    targetWeakness: 'vague_explanation',
  },
  {
    id: 'clarity-elevator-pitch-45',
    title: 'The 45-Second Value Proposition',
    shortDescription: 'Pitch an app, service, or concept with immediate value clarity.',
    whyItMatters: 'Capturing investor or client attention requires instant value differentiation.',
    targetSkill: 'Clarity',
    challengeType: 'concise_answer',
    difficultyLevel: 2,
    difficultyLabel: 'Intermediate',
    durationSeconds: 45,
    prompt: 'Pitch an AI-powered voice coach (like Verblyn) to a busy university student.',
    instructions: [
      'Hook (10s): The burning pain point.',
      'Solution (20s): How the product solves it in minutes a day.',
      'Call to action (15s): The immediate next step.',
    ],
    expectedBehavior: 'Punchy value proposition free of generic fluff.',
    xpReward: 30,
    goalTags: ['WORKPLACE_COMMUNICATION', 'PUBLIC_SPEAKING'],
    targetWeakness: 'weak_opening',
  },
  {
    id: 'clarity-closing-punchline-45',
    title: 'The Memorable Closing Call',
    shortDescription: 'Deliver an explanation that culminates in a clear, memorable call to action.',
    whyItMatters: 'Great presentations fall flat if the ending is vague or trails off.',
    targetSkill: 'Clarity',
    challengeType: 'concise_answer',
    difficultyLevel: 2,
    difficultyLabel: 'Intermediate',
    durationSeconds: 45,
    prompt: 'Argue why your organization should invest more time in weekly knowledge-sharing sessions.',
    instructions: [
      'Lay out the core rationale in the first 30 seconds.',
      'Dedicate the final 15 seconds to a sharp, definitive closing directive.',
      'Finish with vocal firmness and no trailing hesitations.',
    ],
    expectedBehavior: 'Decisive closing sentence that anchors the entire message.',
    xpReward: 30,
    goalTags: ['WORKPLACE_COMMUNICATION', 'PUBLIC_SPEAKING'],
    targetWeakness: 'weak_conclusion',
  },

  // ==========================================
  // --- 3. VOCABULARY & PRECISION (6) ---
  // ==========================================
  {
    id: 'vocab-professional-precision-60',
    title: 'Power Verb Precision',
    shortDescription: 'Describe an achievement using active, precise verbs instead of generic words.',
    whyItMatters: 'Action verbs (orchestrated, streamlined, spearheaded) project high capability.',
    targetSkill: 'Vocabulary',
    challengeType: 'explain_simply',
    difficultyLevel: 2,
    difficultyLabel: 'Intermediate',
    durationSeconds: 60,
    prompt: 'Describe a significant accomplishment. Replace words like "did", "made", "worked on" with precise action verbs.',
    instructions: [
      'Use at least 3 distinct action verbs (e.g. engineered, resolved, accelerated).',
      'Articulate the measurable impact of your work.',
      'Maintain lexical variety without repeating common descriptors.',
    ],
    expectedBehavior: 'High lexical diversity (TTR > 0.65) with descriptive precision.',
    xpReward: 30,
    goalTags: ['JOB_INTERVIEWS', 'CAMPUS_PLACEMENTS', 'WORKPLACE_COMMUNICATION'],
    targetWeakness: 'weak_vocabulary',
  },
  {
    id: 'vocab-analogy-mastery-60',
    title: 'Concrete Metaphor Builder',
    shortDescription: 'Explain an abstract technical concept using vivid physical metaphors.',
    whyItMatters: 'Metaphors bridge unfamiliar technical concepts into intuitive understanding.',
    targetSkill: 'Vocabulary',
    challengeType: 'explain_simply',
    difficultyLevel: 2,
    difficultyLabel: 'Intermediate',
    durationSeconds: 60,
    prompt: 'Explain what Database Indexing or Caching is by comparing it to a physical library or cookbook.',
    instructions: [
      'Explicitly map technical terms to physical items in your metaphor.',
      'Show the difference in speed/efficiency using descriptive sensory language.',
      'Bring it back to the software reality in your final sentence.',
    ],
    expectedBehavior: 'Rich metaphorical descriptors without jargon reliance.',
    xpReward: 30,
    goalTags: ['CAMPUS_PLACEMENTS', 'WORKPLACE_COMMUNICATION'],
    targetWeakness: 'excessive_jargon',
  },
  {
    id: 'vocab-descriptive-impact-45',
    title: 'Sensory Language Drill',
    shortDescription: 'Describe a high-pressure environment using vivid descriptive language.',
    whyItMatters: 'Sensory vocabulary makes storytelling immersive and memorable.',
    targetSkill: 'Vocabulary',
    challengeType: 'timed_speaking',
    difficultyLevel: 1,
    difficultyLabel: 'Beginner',
    durationSeconds: 45,
    prompt: 'Describe the intense atmosphere inside a hospital emergency room or a stock trading floor.',
    instructions: [
      'Incorporate auditory and visual descriptive adjectives.',
      'Avoid overused words like "very busy" or "really fast".',
      'Paint a distinct mental picture for the listener.',
    ],
    expectedBehavior: 'Descriptive, evocative vocabulary with high lexical variety.',
    xpReward: 25,
    goalTags: ['PUBLIC_SPEAKING', 'EVERYDAY_COMMUNICATION'],
    targetWeakness: 'weak_vocabulary',
  },
  {
    id: 'vocab-synonym-expansion-60',
    title: 'Eliminate Repetitive Words',
    shortDescription: 'Speak for 60 seconds about innovation without repeating key adjectives.',
    whyItMatters: 'Repetitive vocabulary makes long speeches tedious and reveals narrow lexical depth.',
    targetSkill: 'Vocabulary',
    challengeType: 'explain_simply',
    difficultyLevel: 2,
    difficultyLabel: 'Intermediate',
    durationSeconds: 60,
    prompt: 'Discuss how artificial intelligence is transforming education and work.',
    instructions: [
      'Never use the words "good", "bad", "big", or "important".',
      'Use sophisticated alternatives (e.g. transformative, pivotal, sub-optimal, substantial).',
      'Keep sentences fluid and natural.',
    ],
    expectedBehavior: 'Zero repeated adjectives; high Type-Token Ratio.',
    xpReward: 30,
    goalTags: ['JOB_INTERVIEWS', 'CAMPUS_PLACEMENTS', 'PUBLIC_SPEAKING'],
    targetWeakness: 'excessive_repetition',
  },
  {
    id: 'vocab-nuanced-qualifiers-75',
    title: 'Nuanced Executive Distinction',
    shortDescription: 'Differentiate between two subtly distinct strategies using precise vocabulary.',
    whyItMatters: 'Senior professionals distinguish between nuance rather than binary black-and-white views.',
    targetSkill: 'Vocabulary',
    challengeType: 'concise_answer',
    difficultyLevel: 3,
    difficultyLabel: 'Advanced',
    durationSeconds: 75,
    prompt: 'Explain the nuanced difference between being efficient vs being effective in project execution.',
    instructions: [
      'Define each concept with surgical lexical precision.',
      'Provide a scenario where an action is efficient but completely ineffective.',
      'Synthesize how high-performing teams balance both.',
    ],
    expectedBehavior: 'Precise, nuanced vocabulary and analytical clarity.',
    xpReward: 35,
    goalTags: ['WORKPLACE_COMMUNICATION', 'JOB_INTERVIEWS'],
    targetWeakness: 'vague_explanation',
  },
  {
    id: 'vocab-data-storytelling-60',
    title: 'Translating Numbers to Impact',
    shortDescription: 'Describe quantitative metrics by connecting data points to human outcomes.',
    whyItMatters: 'Data without narrative leaves listeners cold; storytelling brings metrics to life.',
    targetSkill: 'Vocabulary',
    challengeType: 'explain_simply',
    difficultyLevel: 2,
    difficultyLabel: 'Intermediate',
    durationSeconds: 60,
    prompt: 'Your software reduced page latency from 3.2s to 0.4s and increased retention by 18%. Explain the impact.',
    instructions: [
      'Translate milliseconds into human patience and conversion value.',
      'Explain what an 18% retention lift means for team growth and revenue.',
      'Close with the overarching strategic implication.',
    ],
    expectedBehavior: 'Quantitative precision paired with narrative impact.',
    xpReward: 30,
    goalTags: ['WORKPLACE_COMMUNICATION', 'JOB_INTERVIEWS'],
    targetWeakness: 'insufficient_detail',
  },

  // ==========================================
  // --- 4. GRAMMAR & STRUCTURAL DISCIPLINE (5) ---
  // ==========================================
  {
    id: 'grammar-short-sentence-discipline-45',
    title: 'Short Sentence Sprint',
    shortDescription: 'Speak in disciplined sentences of 8 to 14 words each.',
    whyItMatters: 'Run-on sentences cause listener fatigue and make arguments hard to follow.',
    targetSkill: 'Grammar',
    challengeType: 'timed_speaking',
    difficultyLevel: 1,
    difficultyLabel: 'Beginner',
    durationSeconds: 45,
    prompt: 'Explain why regular physical exercise improves cognitive focus at work.',
    instructions: [
      'Keep every sentence under 14 words.',
      'End each sentence with a clean drop in vocal inflection.',
      'Never chain clauses together with "and then... and also...".',
    ],
    expectedBehavior: 'Average sentence length between 9 and 14 words.',
    xpReward: 25,
    goalTags: ['EVERYDAY_COMMUNICATION', 'PUBLIC_SPEAKING'],
    targetWeakness: 'grammar_errors',
  },
  {
    id: 'grammar-prep-framework-60',
    title: 'Point-Reason-Example-Point (PREP)',
    shortDescription: 'Structure an argumentative answer using the rigorous PREP formula.',
    whyItMatters: 'PREP guarantees tight logical cohesion without rambling.',
    targetSkill: 'Grammar',
    challengeType: 'concise_answer',
    difficultyLevel: 2,
    difficultyLabel: 'Intermediate',
    durationSeconds: 60,
    prompt: 'Should companies enforce a strict 4-day workweek? State and defend your view.',
    instructions: [
      'P (Point, 10s): Your core stance.',
      'R (Reason, 15s): The primary underlying driver.',
      'E (Example, 25s): A concrete real-world example or study.',
      'P (Point, 10s): Restate your thesis with finality.',
    ],
    expectedBehavior: 'Flawless execution of PREP 4-part structure.',
    xpReward: 30,
    goalTags: ['GROUP_DISCUSSIONS', 'JOB_INTERVIEWS', 'PUBLIC_SPEAKING'],
    targetWeakness: 'unclear_structure',
  },
  {
    id: 'grammar-active-voice-focus-60',
    title: 'Active Voice Authority',
    shortDescription: 'Deliver a retrospective without using passive voice phrasing.',
    whyItMatters: 'Active voice demonstrates ownership, directness, and executive confidence.',
    targetSkill: 'Grammar',
    challengeType: 'explain_simply',
    difficultyLevel: 2,
    difficultyLabel: 'Intermediate',
    durationSeconds: 60,
    prompt: 'Describe a situation where an error occurred in your team and how it was remediated.',
    instructions: [
      'Do not say "mistakes were made" or "it was decided".',
      'Name specific actors: "I investigated...", "Our team restructured...", "We deployed...".',
      'Maintain strong subject-verb alignment throughout.',
    ],
    expectedBehavior: '100% active voice structure with clear agency.',
    xpReward: 30,
    goalTags: ['WORKPLACE_COMMUNICATION', 'JOB_INTERVIEWS'],
    targetWeakness: 'grammar_errors',
  },
  {
    id: 'grammar-clause-economy-45',
    title: 'Compound Sentence Trimming',
    shortDescription: 'Trim wordy explanations into crisp, decisive claims.',
    whyItMatters: 'Eliminating filler clauses increases audience retention.',
    targetSkill: 'Grammar',
    challengeType: 'concise_answer',
    difficultyLevel: 3,
    difficultyLabel: 'Advanced',
    durationSeconds: 45,
    prompt: 'Why is unit testing critical before deploying code to production?',
    instructions: [
      'Deliver 4 distinct, powerful assertions in 45 seconds.',
      'Avoid qualifying preambles like "I feel that essentially what happens is...".',
      'State raw facts and direct cause-and-effect relationships.',
    ],
    expectedBehavior: 'High information density free from rambling qualifying phrases.',
    xpReward: 30,
    goalTags: ['CAMPUS_PLACEMENTS', 'WORKPLACE_COMMUNICATION'],
    targetWeakness: 'overlong_answers',
  },
  {
    id: 'grammar-transition-flow-60',
    title: 'Seamless Signposting Words',
    shortDescription: 'Use formal transitional signposts (Furthermore, Consequently, In contrast).',
    whyItMatters: 'Signposting gives speeches an architectural roadmap that listeners easily track.',
    targetSkill: 'Grammar',
    challengeType: 'explain_simply',
    difficultyLevel: 2,
    difficultyLabel: 'Intermediate',
    durationSeconds: 60,
    prompt: 'Compare working in an early-stage startup versus an established corporate enterprise.',
    instructions: [
      'Use "On one hand..." for the startup perspective.',
      'Use "Conversely / In contrast..." to pivot to enterprise.',
      'Use "Ultimately / Therefore..." for your closing synthesis.',
    ],
    expectedBehavior: 'Explicit logical signposting connecting all arguments.',
    xpReward: 30,
    goalTags: ['GROUP_DISCUSSIONS', 'JOB_INTERVIEWS'],
    targetWeakness: 'unclear_structure',
  },

  // ==========================================
  // --- 5. CONFIDENCE & VOCAL DELIVERY (6) ---
  // ==========================================
  {
    id: 'confidence-assertive-opinion-60',
    title: 'Defend a Controversial View',
    shortDescription: 'State a clear opinion and back it up with two compelling arguments in 60 seconds.',
    whyItMatters: 'Eliminates apologetic hedging words like "I guess" or "sort of".',
    targetSkill: 'Confidence',
    challengeType: 'concise_answer',
    difficultyLevel: 2,
    difficultyLabel: 'Intermediate',
    durationSeconds: 60,
    prompt: 'Pick a trend in technology, work, or education that you disagree with and explain why with two reasons.',
    instructions: [
      'Open with an unambiguous thesis statement in the first 10 seconds.',
      'Support with Reason 1 (20s) and Reason 2 (20s).',
      'Close decisively without trailing off.',
    ],
    expectedBehavior: 'Firm vocal assertion free from passive hedging language.',
    xpReward: 30,
    goalTags: ['GROUP_DISCUSSIONS', 'WORKPLACE_COMMUNICATION', 'PUBLIC_SPEAKING'],
    targetWeakness: 'filler_dependency',
  },
  {
    id: 'confidence-eliminating-hedges-45',
    title: 'Zero-Hedge Direct Stance',
    shortDescription: 'Answer a difficult question without using softeners ("I think", "maybe", "sort of").',
    whyItMatters: 'Hedging language dilutes authority and undermines credibility.',
    targetSkill: 'Confidence',
    challengeType: 'concise_answer',
    difficultyLevel: 1,
    difficultyLabel: 'Beginner',
    durationSeconds: 45,
    prompt: 'Will AI replace software engineers within 5 years? Give a definitive yes or no and defend it.',
    instructions: [
      'Never say "I think", "I feel", "in my humble opinion", or "it kind of depends".',
      'State direct, declarative sentences: "AI will accelerate productivity, not replace engineers, because...".',
      'Deliver with calm conviction.',
    ],
    expectedBehavior: 'Zero hedging qualifiers with firm delivery.',
    xpReward: 25,
    goalTags: ['GROUP_DISCUSSIONS', 'JOB_INTERVIEWS'],
    targetWeakness: 'filler_dependency',
  },
  {
    id: 'confidence-unpopular-truth-60',
    title: 'Delivering Uncomfortable Feedback',
    shortDescription: 'Deliver constructive, direct feedback with professional empathy and firmness.',
    whyItMatters: 'Difficult conversations require balancing clarity with professionalism.',
    targetSkill: 'Confidence',
    challengeType: 'concise_answer',
    difficultyLevel: 3,
    difficultyLabel: 'Advanced',
    durationSeconds: 60,
    prompt: 'Tell a peer that their recent missed deadlines are impacting the whole team project.',
    instructions: [
      'State the observable fact without accusation (15s).',
      'Explain the team-wide consequence (25s).',
      'Propose a collaborative path forward (20s).',
    ],
    expectedBehavior: 'Assertive, non-apologetic tone maintaining professional respect.',
    xpReward: 35,
    goalTags: ['WORKPLACE_COMMUNICATION', 'PUBLIC_SPEAKING'],
    targetWeakness: 'weak_opening',
  },
  {
    id: 'confidence-high-stakes-qna-45',
    title: 'Spontaneous Objection Handling',
    shortDescription: 'Defend your project timeline against a skeptical client or manager.',
    whyItMatters: 'Composure under fire distinguishes reliable leaders from panicked responders.',
    targetSkill: 'Confidence',
    challengeType: 'rapid_response',
    difficultyLevel: 3,
    difficultyLabel: 'Advanced',
    durationSeconds: 45,
    prompt: 'Stakeholder says: "This timeline is twice as long as we expected. Why should we approve this?"',
    instructions: [
      'Acknowledge the urgency without becoming defensive (10s).',
      'Explain the quality and risk mitigation built into the timeline (25s).',
      'Offer a phased tradeoff option (10s).',
    ],
    expectedBehavior: 'Composed, steady cadence under simulated adversarial pressure.',
    xpReward: 35,
    goalTags: ['WORKPLACE_COMMUNICATION', 'JOB_INTERVIEWS'],
    targetWeakness: 'slow_delivery',
  },
  {
    id: 'confidence-vocal-conviction-60',
    title: 'Decisive Recommendation Delivery',
    shortDescription: 'Pitch an expensive strategic pivot with uncompromising conviction.',
    whyItMatters: 'If the speaker sounds uncertain, the decision-maker will never approve the risk.',
    targetSkill: 'Confidence',
    challengeType: 'concise_answer',
    difficultyLevel: 2,
    difficultyLabel: 'Intermediate',
    durationSeconds: 60,
    prompt: 'Convince leadership to rewrite a legacy software system from scratch.',
    instructions: [
      'Anchor on the hidden cost of technical debt (20s).',
      'Show the breakthrough velocity of modern architecture (25s).',
      'Conclude with an unambiguous call to action (15s).',
    ],
    expectedBehavior: 'High conviction vocal energy with zero hesitation sounds.',
    xpReward: 30,
    goalTags: ['WORKPLACE_COMMUNICATION', 'JOB_INTERVIEWS'],
    targetWeakness: 'weak_conclusion',
  },
  {
    id: 'confidence-crisis-handling-90',
    title: 'Leadership Under Pressure',
    shortDescription: 'Address an anxious team during a severe product outage or company crisis.',
    whyItMatters: 'In a crisis, tone and vocal stability matter as much as the actual facts.',
    targetSkill: 'Confidence',
    challengeType: 'timed_speaking',
    difficultyLevel: 3,
    difficultyLabel: 'Advanced',
    durationSeconds: 90,
    prompt: 'Your flagship product is down for major enterprise customers. Brief your engineering team on the incident response.',
    instructions: [
      'Calm the room with transparent truth (30s).',
      'Assign immediate triage swimlanes (35s).',
      'Establish communication protocols and close with confidence (25s).',
    ],
    expectedBehavior: 'Authoritative, calm, grounding pacing throughout 90 seconds.',
    xpReward: 45,
    goalTags: ['WORKPLACE_COMMUNICATION', 'PUBLIC_SPEAKING'],
    targetWeakness: 'rushed_delivery',
  },

  // ==========================================
  // --- 6. INTERVIEW & CAREER MASTERY (7) ---
  // ==========================================
  {
    id: 'interview-tell-me-about-yourself-60',
    title: 'The "Tell Me About Yourself" Hook',
    shortDescription: 'Deliver a crisp 60-second self-introduction tailored for recruiters.',
    whyItMatters: 'First impressions in interviews set the tone for the entire conversation.',
    targetSkill: 'Clarity',
    challengeType: 'interview_answer',
    difficultyLevel: 1,
    difficultyLabel: 'Beginner',
    durationSeconds: 60,
    prompt: 'Answer: "Tell me about yourself, your background, and what excites you right now."',
    instructions: [
      'Present (20s): Current role/studies and core expertise.',
      'Past (20s): 1 standout milestone or formative experience.',
      'Future (20s): Why you are excited about upcoming opportunities.',
    ],
    expectedBehavior: 'Present-Past-Future narrative structure with confidence.',
    xpReward: 30,
    goalTags: ['JOB_INTERVIEWS', 'CAMPUS_PLACEMENTS'],
    targetWeakness: 'weak_opening',
  },
  {
    id: 'interview-star-behavioral-90',
    title: 'STAR Conflict Resolution',
    shortDescription: 'Structure a behavioral interview response using Situation, Task, Action, and Result.',
    whyItMatters: 'STAR method prevents rambling and ensures you provide concrete behavioral evidence.',
    targetSkill: 'Confidence',
    challengeType: 'interview_answer',
    difficultyLevel: 3,
    difficultyLabel: 'Advanced',
    durationSeconds: 90,
    prompt: 'Describe a time you disagreed with a colleague or teammate on an approach and how you resolved it.',
    instructions: [
      'Situation & Task (25s): The context and the point of disagreement.',
      'Action (40s): How you initiated a constructive conversation.',
      'Result (25s): The mutual outcome and what was learned.',
    ],
    expectedBehavior: 'Evenly apportioned STAR delivery without rambling.',
    xpReward: 35,
    goalTags: ['JOB_INTERVIEWS', 'CAMPUS_PLACEMENTS', 'WORKPLACE_COMMUNICATION'],
    targetWeakness: 'unclear_structure',
  },
  {
    id: 'interview-why-hire-you-60',
    title: 'Why Should We Hire You?',
    shortDescription: 'Articulate your unique value proposition without sounding arrogant or generic.',
    whyItMatters: 'Differentiates you from dozens of candidates with identical resumes.',
    targetSkill: 'Clarity',
    challengeType: 'interview_answer',
    difficultyLevel: 2,
    difficultyLabel: 'Intermediate',
    durationSeconds: 60,
    prompt: 'Answer: "With so many qualified candidates, why should we select you for this role?"',
    instructions: [
      'Highlight 1 distinct technical/execution superpower (25s).',
      'Highlight 1 cultural/communication superpower (20s).',
      'Close with your immediate commitment to day-1 impact (15s).',
    ],
    expectedBehavior: 'Targeted value alignment tailored to team needs.',
    xpReward: 30,
    goalTags: ['JOB_INTERVIEWS', 'CAMPUS_PLACEMENTS'],
    targetWeakness: 'weak_opening',
  },
  {
    id: 'interview-greatest-failure-75',
    title: 'The Turnaround Failure Story',
    shortDescription: 'Discuss a genuine mistake, what you learned, and how you turned it into a strength.',
    whyItMatters: 'Tests self-awareness, humility, resilience, and growth mindset.',
    targetSkill: 'Fluency',
    challengeType: 'interview_answer',
    difficultyLevel: 3,
    difficultyLabel: 'Advanced',
    durationSeconds: 75,
    prompt: 'Describe a project that failed or did not meet expectations. What was your role and what changed?',
    instructions: [
      'Own the mistake clearly without blaming external teammates (20s).',
      'Detail the immediate corrective action taken (30s).',
      'Explain the permanent system or habit you adopted as a result (25s).',
    ],
    expectedBehavior: 'Authentic accountability and clear growth narrative.',
    xpReward: 35,
    goalTags: ['JOB_INTERVIEWS', 'CAMPUS_PLACEMENTS'],
    targetWeakness: 'insufficient_detail',
  },
  {
    id: 'interview-salary-value-defense-60',
    title: 'Articulating Your Market Value',
    shortDescription: 'State and justify your compensation expectations with professionalism and data.',
    whyItMatters: 'Negotiation confidence directly impacts career trajectory and earnings.',
    targetSkill: 'Confidence',
    challengeType: 'interview_answer',
    difficultyLevel: 2,
    difficultyLabel: 'Intermediate',
    durationSeconds: 60,
    prompt: 'Answer: "What are your salary expectations for this position and how did you arrive at that number?"',
    instructions: [
      'Anchor to industry benchmarking and market data (20s).',
      'Connect the number to the unique multiplier impact you deliver (25s).',
      'Leave room for holistic package discussion (15s).',
    ],
    expectedBehavior: 'Polite, firm, data-backed justification without apologetic qualifiers.',
    xpReward: 30,
    goalTags: ['JOB_INTERVIEWS', 'WORKPLACE_COMMUNICATION'],
    targetWeakness: 'weak_opening',
  },
  {
    id: 'interview-technical-deepdive-90',
    title: 'System Architecture Deep Dive',
    shortDescription: 'Explain your most complex technical architecture from high level down to trade-offs.',
    whyItMatters: 'Senior engineering interviews test depth of technical design and trade-off justification.',
    targetSkill: 'Clarity',
    challengeType: 'interview_answer',
    difficultyLevel: 3,
    difficultyLabel: 'Advanced',
    durationSeconds: 90,
    prompt: 'Describe the technical architecture of the most complex system you have designed or worked on.',
    instructions: [
      'High level overview & business requirements (25s).',
      'Key architectural choices (databases, caching, queues) (40s).',
      'The hardest trade-off you had to accept and why (25s).',
    ],
    expectedBehavior: 'High technical rigor, structured transitions, and clear trade-off rationale.',
    xpReward: 45,
    goalTags: ['CAMPUS_PLACEMENTS', 'JOB_INTERVIEWS'],
    targetWeakness: 'vague_explanation',
  },
  {
    id: 'interview-vision-future-60',
    title: 'Where Do You See Yourself in 3 Years?',
    shortDescription: 'Share realistic, ambitious career goals aligned with role growth.',
    whyItMatters: 'Recruiters assess ambition, commitment, and alignment with organizational needs.',
    targetSkill: 'Fluency',
    challengeType: 'interview_answer',
    difficultyLevel: 1,
    difficultyLabel: 'Beginner',
    durationSeconds: 60,
    prompt: 'Answer: "Where do you see yourself professionally in 3 to 5 years?"',
    instructions: [
      'Year 1: Mastery of role and team impact (20s).',
      'Year 2-3: Taking on broader ownership and mentoring (25s).',
      'Long term: The domain mastery you aim to achieve (15s).',
    ],
    expectedBehavior: 'Realistic ambition tied directly to practical skills growth.',
    xpReward: 30,
    goalTags: ['JOB_INTERVIEWS', 'CAMPUS_PLACEMENTS'],
    targetWeakness: 'weak_conclusion',
  },
];

