// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Safe environment resolution for Vite and test runners
const env = typeof import.meta !== 'undefined' && import.meta.env ? import.meta.env : (process.env as Record<string, string | undefined>) || {};
const SUPABASE_URL = env.VITE_SUPABASE_URL || 'https://mock.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = env.VITE_SUPABASE_PUBLISHABLE_KEY || 'mock-key';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof localStorage !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});